name: scorers
channels:
  - conda-forge
  - rdkit/label/nightly
  - defaults
  - lich
dependencies:
  - python=3.7
  - rdkit
  - pip
  - syba
  - lightgbm
  - pip:
    - git+https://github.com/reymond-group/RAscore.git@master
    - sqlitedict
  - scikit-learn=1.0.2 # install manually later