#!/bin/bash
ARG="$1"
shift 1
case "$ARG" in
	main)
		${CONDA_PREFIX}/envs/py3.10/bin/python -m main.main
    ;;
  dummy_scorings)
		${CONDA_PREFIX}/envs/py3.10/bin/python -m main.main dummy_scorings
    ;;
	test)
		${CONDA_PREFIX}/envs/py3.10/bin/python -m main.test
    ;;
	format)
		${CONDA_PREFIX}/envs/py3.10/bin/black *.py **/*.py
		${CONDA_PREFIX}/envs/py3.10/bin/isort *.py **/*.py
		;;
  stats_detailed)
    time ${CONDA_PREFIX}/envs/py3.10/bin/jupyter nbconvert \
      --execute --to notebook --inplace stats_detailed.ipynb
    ;;
  stats)
    time ${CONDA_PREFIX}/envs/py3.10/bin/jupyter nbconvert \
      --execute --to notebook --inplace stats.ipynb
    ;;
  stats_selected)
    time ${CONDA_PREFIX}/envs/py3.10/bin/jupyter nbconvert \
      --execute --to notebook --inplace stats_selected.ipynb
    ;;
  ai)
    ${CONDA_PREFIX}/envs/aizynth-env/bin/python -m ai.main
    ;;
esac
